baseURL = "https://husnaram.github.io/"
languageCode = "en-us"
title = "Husnaram"
theme = "horlog"
copyright = "© Husnaram"
enableRobotsTXT = true
canonifyURLs = true

# Code highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Posts per page
paginate = 5

# Using emoji
enableEmoji = true

[build]
writeStats = true

[params]
    slogan = "a seasoned enthusiast of developer"
    interjection = "Hello folks"
    introduction = "Hi! I'm Husna by the way. An enthusiasts in web programming. But not a professional, but still want to be the expert. And learning is the way to reach out!"
    skills = [
        "HTML/CSS",
        "Tailwindcss",
        "Javascript",
        "Laravel",
        "PHP",
        "Golang",
        "MySQL",
    ]
    [[params.social]]
    name = "GitHub"
    icon = """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>"""
    url = "https://github.com/husnaram"

    [[params.social]]
    name = "Twitter"
    icon = """<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>"""
    url = "https://twitter.com/husna_ram/"


[menu]
    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

    [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3

    [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
